services:
  - type: web
    name: takecharge-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 10000
      - key: ADMIN_PASSWORD
        sync: false
      - key: NODE_ENV
        value: production 