services:
  - type: web
    name: takecharge-backend
    env: node
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && npm install && mkdir -p public && cp -r ../frontend/dist/* public/
    startCommand: cd backend && node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 10000
      - key: ADMIN_PASSWORD
        sync: false
      - key: NODE_ENV
        value: production 