services:
  - type: web
    name: takecharge-backend
    env: node
    buildCommand: |
      echo "Starting build process..."
      cd frontend
      echo "Installing frontend dependencies..."
      npm install
      echo "Building frontend..."
      npm run build
      echo "Frontend build complete"
      cd ../backend
      echo "Installing backend dependencies..."
      npm install
      echo "Creating public directory..."
      mkdir -p public
      echo "Copying frontend build files..."
      cp -r ../frontend/dist/* public/
      echo "Build process complete"
    startCommand: cd backend && node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 10000
      - key: ADMIN_PASSWORD
        sync: false
      - key: NODE_ENV
        value: production 