services:
  - type: web
    name: takecharge-backend
    env: node
    nodeVersion: 18.17.0
    buildCommand: |
      echo "Current directory: $(pwd)"
      echo "Installing root dependencies..."
      npm install
      echo "Installing frontend dependencies..."
      cd frontend && npm install
      echo "Building frontend..."
      npm run build
      echo "Installing backend dependencies..."
      cd ../backend && npm install
      echo "Build phase completed"
    startCommand: cd backend && node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 10000
      - key: ADMIN_PASSWORD
        sync: false
      - key: NODE_ENV
        value: production
      - key: PATH
        value: /opt/render/project/src/frontend/node_modules/.bin:$PATH 